### ISSUE TITLE
i am trying to pass variable but not working properly

### ISSUE THREAD

**Issue by zeel-micronstars** [ash2shukla/PyZIPIN#1]
it is showing me this error

396050
the JSON object must be str, bytes or bytearray, not NoneType
 Dharampur
invalid literal for int() with base 10: ' Dharampur'
 500018
the JSON object must be str, bytes or bytearray, not NoneType
 Hyderabad

**Comment by ash2shukla** [comment]
https://github.com/ravigoel08/pyzipcin

Please use this package, i am not maintaining this package anymore.
